import {
  IsString,
  IsNumber,
  IsPositive,
  IsEnum,
  IsOptional,
  IsBoolean,
  IsDateString,
  IsIP,
  Min,
  Max,
  Length,
  Matches,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { RiskLevel, TransactionStatus } from '../schemas/transaction.schema';

// ─────────────────────────────────────────────────────────────────────────────
// transaction.dto.ts
//
// All DTOs live in one file for Part 1 to keep things navigable.
// As the project grows each DTO can be split into its own file.
//
// Validation strategy:
//  • class-validator decorators enforce shape at the HTTP boundary.
//  • Swagger decorators generate the OpenAPI spec automatically (NestJS plugin).
//  • Transformation (class-transformer) converts strings → numbers / dates.
// ─────────────────────────────────────────────────────────────────────────────

// ── VPA regex: <handle>@<bank>  e.g. vakar@oksbi ────────────────────────────
const VPA_REGEX = /^[a-zA-Z0-9._-]+@[a-zA-Z]+$/;

// ── 1. CreateTransactionDto ──────────────────────────────────────────────────
export class CreateTransactionDto {

  @ApiProperty({
    example: 'UPI1712345678901',
    description: 'Unique UPI transaction reference ID generated by the PSP',
  })
  @IsString()
  @Length(8, 64)
  txnId: string;

  @ApiProperty({ example: 'vakar@oksbi', description: 'Sender VPA' })
  @IsString()
  @Matches(VPA_REGEX, { message: 'senderId must be a valid VPA (e.g. user@bank)' })
  senderId: string;

  @ApiProperty({ example: 'merchant@hdfc', description: 'Receiver VPA' })
  @IsString()
  @Matches(VPA_REGEX, { message: 'receiverId must be a valid VPA (e.g. merchant@bank)' })
  receiverId: string;

  @ApiProperty({ example: 15000, description: 'Amount in INR paise (₹150.00 = 15000)' })
  @IsNumber()
  @IsPositive()
  amount: number;

  @ApiPropertyOptional({ example: 'INR', default: 'INR' })
  @IsOptional()
  @IsString()
  currency?: string;

  @ApiProperty({ example: 'DV-A1B2C3D4', description: 'Device fingerprint ID' })
  @IsString()
  deviceId: string;

  @ApiProperty({ example: 'Mumbai' })
  @IsString()
  city: string;

  @ApiProperty({ example: 'Maharashtra' })
  @IsString()
  state: string;

  @ApiPropertyOptional({ example: '103.21.58.12' })
  @IsOptional()
  @IsIP()
  ipAddress?: string;

  @ApiPropertyOptional({ example: 'Android 13 / Samsung Galaxy S23' })
  @IsOptional()
  @IsString()
  deviceModel?: string;

  @ApiProperty({
    example: '2024-04-09T02:35:00.000Z',
    description: 'ISO 8601 timestamp of the actual UPI transaction',
  })
  @IsDateString()
  transactionTime: string;
}

// ── 2. UpdateRiskDto  (written by the queue processor, not the HTTP layer) ──
export class UpdateRiskDto {

  @ApiProperty({ enum: RiskLevel })
  @IsEnum(RiskLevel)
  riskLevel: RiskLevel;

  @ApiProperty({ example: 78, description: 'ML risk score 0–100' })
  @IsNumber()
  @Min(0)
  @Max(100)
  riskScore: number;

  @ApiProperty({ example: { unusual_amount: true, odd_hour: true } })
  fraudSignals: Record<string, boolean | number>;

  @ApiProperty({ example: 'High amount at odd hour to new recipient' })
  @IsString()
  riskReason: string;

  @ApiProperty({ enum: TransactionStatus })
  @IsEnum(TransactionStatus)
  status: TransactionStatus;

  scoredAt: Date;
}

// ── 3. QueryTransactionDto  (used for list / filter endpoint) ────────────────
export class QueryTransactionDto {

  @ApiPropertyOptional({ enum: RiskLevel, description: 'Filter by risk level' })
  @IsOptional()
  @IsEnum(RiskLevel)
  riskLevel?: RiskLevel;

  @ApiPropertyOptional({ enum: TransactionStatus })
  @IsOptional()
  @IsEnum(TransactionStatus)
  status?: TransactionStatus;

  @ApiPropertyOptional({ example: 'vakar@oksbi' })
  @IsOptional()
  @IsString()
  senderId?: string;

  @ApiPropertyOptional({ example: '2024-04-01T00:00:00.000Z', description: 'From date (ISO)' })
  @IsOptional()
  @IsDateString()
  from?: string;

  @ApiPropertyOptional({ example: '2024-04-09T23:59:59.000Z', description: 'To date (ISO)' })
  @IsOptional()
  @IsDateString()
  to?: string;

  @ApiPropertyOptional({ example: 1, default: 1, description: 'Page number' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  page?: number = 1;

  @ApiPropertyOptional({ example: 20, default: 20, description: 'Items per page (max 100)' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  @Max(100)
  limit?: number = 20;

  @ApiPropertyOptional({
    example: 'createdAt',
    enum: ['createdAt', 'amount', 'riskScore'],
    default: 'createdAt',
  })
  @IsOptional()
  @IsString()
  sortBy?: string = 'createdAt';

  @ApiPropertyOptional({ example: 'desc', enum: ['asc', 'desc'], default: 'desc' })
  @IsOptional()
  @IsString()
  sortOrder?: 'asc' | 'desc' = 'desc';
}

// ── 4. BulkUploadDto  (CSV upload – used in Part 2 when we add file handling) ──
export class BulkUploadResponseDto {
  @ApiProperty({ example: 150 })
  total: number;

  @ApiProperty({ example: 148 })
  accepted: number;

  @ApiProperty({ example: 2 })
  rejected: number;

  @ApiProperty({ example: ['Row 3: invalid VPA format', 'Row 91: amount must be positive'] })
  errors: string[];

  @ApiProperty({ example: 'bulk-upload-job-uuid' })
  jobId: string;
}

// ── 5. Paginated response wrapper ────────────────────────────────────────────
export class PaginatedResponseDto<T> {
  data: T[];

  @ApiProperty({ example: 342 })
  total: number;

  @ApiProperty({ example: 1 })
  page: number;

  @ApiProperty({ example: 20 })
  limit: number;

  @ApiProperty({ example: 18 })
  totalPages: number;
}